[package]
name = "raft"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
bytes = { version = "1", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
rand = "0.8.5"
env_logger = "0.11.5"
log = "0.4.22"
